# Build stage
FROM golang:1.24.5-alpine3.22 AS builder

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Build the producer
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o producer ./cmd/producer

# Final stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

# Copy the binary from builder stage
COPY --from=builder /app/producer .

CMD ["./producer"]
