FROM python:3.12.11-alpine

WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the producer script
COPY producer.py .

# Copy the logger module
COPY utils/logger.py utils/logger.py

# Make the script executable
RUN chmod +x producer.py

# Run the producer
CMD ["python", "producer.py"]
