services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # RabbitMQ default port
      - "15672:15672"   # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_net

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    container_name: producer
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672/
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    networks:
      - rabbitmq_net

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: consumer
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672/
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    networks:
      - rabbitmq_net

volumes:
  rabbitmq_data:

networks:
  rabbitmq_net:
    driver: bridge
